# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: cosmos-db-nosql-dotnet-quickstart
services:
  web:
    project: ./src/web
    language: csharp
    host: containerapp
    docker:
      path: ./Dockerfile
      context: ./
  api:
    project: ./src/api
    language: csharp
    host: containerapp
    docker:
      path: ./Dockerfile
      context: ./
pipeline:
  provider: github
hooks:
  postprovision:
    windows:
      run: |
        dotnet user-secrets set "AZURE_COSMOS_DB_NOSQL_ENDPOINT" "$env:AZURE_COSMOS_ENDPOINT" --project ./src/api/Cosmos.Samples.NoSQL.Quickstart.Api.csproj
      shell: pwsh
      continueOnError: false
      interactive: true
    posix:
      run: |
        dotnet user-secrets set "AZURE_COSMOS_DB_NOSQL_ENDPOINT" "$AZURE_COSMOS_ENDPOINT" --project ./src/api/Cosmos.Samples.NoSQL.Quickstart.Api.csproj
      shell: sh
      continueOnError: false
      interactive: true